# Generated by Django 5.0.14 on 2025-08-23 12:13

import datetime
import django.db.models.deletion
import django.utils.timezone
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('parents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default=students.models.generate_unique_student_id, editable=False, help_text='A unique identifier for every student in the table', max_length=20, primary_key=True, serialize=False)),
                ('student_admission_number', models.CharField(default='XXXXX', help_text='Unique number given to student after registration', max_length=30, unique=True)),
                ('student_assessment_number', models.CharField(default='XXXXX', help_text='Unique number given to the student by the state', max_length=20, unique=True)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Students gender i.e male or female no ninary stuff', max_length=10)),
                ('student_dob', models.DateField(default=datetime.date(2000, 1, 1), help_text="Student's date of birth")),
                ('student_phone', models.CharField(blank=True, help_text='Student phone no .i.e optional but recommended', max_length=20, null=True)),
                ('student_status', models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Graduated', 'Graduated'), ('Suspended', 'Suspended')], default='Active', help_text='Student status in school', max_length=15)),
                ('student_enrollment_date', models.DateField(default=datetime.date.today, help_text='The date the student was enrolled')),
                ('student_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Student record creation timestamp')),
                ('student_update', models.DateTimeField(auto_now=True, help_text='Last record update timestamp')),
                ('student_class', models.ForeignKey(blank=True, help_text='the class the student is currently enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.schoolclass')),
                ('student_guardian1', models.ForeignKey(blank=True, help_text='Primary guardian(1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primay_students', to='parents.parent')),
                ('student_guardian2', models.ForeignKey(blank=True, help_text='Secondary guradian(2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_students', to='parents.parent')),
                ('student_school', models.ForeignKey(blank=True, help_text='the school the student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
                ('user', models.OneToOneField(blank=True, help_text='User defined', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
