# Generated by Django 5.0.14 on 2025-08-22 08:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('parents', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_admission_number',
            field=models.CharField(default='XXXXX', help_text='Unique number given to student after registration', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_assessment_number',
            field=models.CharField(default='XXXXX', help_text='Unique number given to the student by the state', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='the class the student is currently enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Student record creation timestamp'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_dob',
            field=models.DateField(default=datetime.date(2000, 1, 1), help_text="Student's date of birth"),
        ),
        migrations.AddField(
            model_name='student',
            name='student_enrollment_date',
            field=models.DateField(default=datetime.date.today, help_text='The date the student was enrolled'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Students gender i.e male or female no ninary stuff', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='student_guardian1',
            field=models.ForeignKey(blank=True, help_text='Primary guardian(1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primay_students', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_guardian2',
            field=models.ForeignKey(blank=True, help_text='Secondary guradian(2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_students', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, help_text='Student phone no .i.e optional but recommended', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_school',
            field=models.ForeignKey(blank=True, help_text='the school the student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Graduated', 'Graduated'), ('Suspended', 'Suspended')], default='Active', help_text='Student status in school', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='student_update',
            field=models.DateTimeField(auto_now=True, help_text='Last record update timestamp'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User defined', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
