# Generated by Django 5.0.14 on 2025-08-23 07:23

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=students.models.generate_unique_student_id, editable=False, help_text='A unique identifier for every student in the table', max_length=20, primary_key=True, serialize=False),
        ),
    ]
