# Generated by Django 5.0.14 on 2025-08-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_club_status'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_club',
            field=models.ForeignKey(blank=True, help_text='the club the student is currently enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='clubs.club'),
        ),
    ]
