# Generated by Django 5.0.14 on 2025-08-23 06:13

import django.db.models.deletion
import teachers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(default=teachers.models.generate_unique_teacher_id, help_text='A unique identifier for the teacher in the sys', max_length=20, primary_key=True, serialize=False)),
                ('teacher_tsc_number', models.CharField(blank=True, help_text="Teacher's tsc assigned number", max_length=30, null=True)),
                ('teacher_phone', models.CharField(help_text="Teacher's phone number", max_length=20)),
                ('teacher_role', models.CharField(choices=[('Principal', 'Principal'), ('Deputy', 'Deputy'), ('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher'), ('Patron', 'Patron')], help_text='The title of the teacher in the school', max_length=30)),
                ('teacher_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Retired', 'Retired')], default='Active', help_text='Teachers employment status', max_length=15)),
                ('teacher_dob', models.DateField(blank=True, help_text='Optional D.O.B for compliance reporting ', null=True)),
                ('teacher_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Male or female only ! no binary stuff', max_length=10)),
                ('teacher_hire_date', models.DateField(help_text='The date that the teacher was hired in the school')),
                ('teacher_creation_date', models.DateTimeField(auto_now_add=True, help_text='Simply the day the teacher was added into the system')),
                ('teacher_updated_date', models.DateTimeField(auto_now=True, help_text='Last time the record was updated')),
                ('teacher_school', models.ForeignKey(help_text='The school from which teh teacher belongs', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
