# Generated by Django 5.0.14 on 2025-08-23 07:23

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=teachers.models.generate_unique_teacher_id, editable=False, help_text='A unique identifier for the teacher in the sys', max_length=20, primary_key=True, serialize=False),
        ),
    ]
