# Generated by Django 5.0.14 on 2025-08-23 08:10

import courses.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level'),
        ('schools', '0002_alter_school_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=courses.models.generate_unique_course_id, editable=False, help_text='Unique course id for each in the school', max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='Name of the course', max_length=100, unique=True)),
                ('course_description', models.TextField(blank=True, help_text='Course description', null=True)),
                ('course_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], help_text='Availability or unavailability of the course', max_length=15)),
                ('course_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the course was created')),
                ('course_update_date', models.DateTimeField(auto_now=True, help_text='The last record update')),
                ('course_level', models.ForeignKey(help_text='The level of the course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.schoolclass', to_field='class_level')),
                ('course_school', models.ForeignKey(help_text='Courses offered in the schools', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school')),
            ],
        ),
    ]
