# Generated by Django 5.0.14 on 2025-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('PRE-PRIMARY-EDUCATION', 'PRE-PRIMARY-EDUCATION'), ('JUNIOR-SECONDARY-EDUCATION', 'JUNIOR-SECONDARY-EDUCATION'), ('SENIOR-SECONDARY-EDUCATION', 'SENIOR-SECONDARY-EDUCATION'), ('OTHER', 'OTHER')], db_index=True, help_text='Name of the course', max_length=50, unique=True),
        ),
    ]
