# Generated by Django 5.0.14 on 2025-08-31 08:32

import django.db.models.deletion
import django.utils.timezone
import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(default=subjects.models.generate_unique_subject_id, help_text='Subject ID', max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_index=True, help_text='This is the name of the subject', max_length=100)),
                ('subject_code', models.CharField(blank=True, help_text=' Optional Program short code e.g CIT-001', max_length=20, null=True, unique=True)),
                ('subject_description', models.TextField(blank=True, help_text='Description of the subject', max_length=300, null=True)),
                ('subject_status', models.CharField(choices=[('Active', 'Active'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Available', help_text='Aailable for registration or !', max_length=20)),
                ('subject_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Subject creation Timestamp')),
                ('subject_update_date', models.DateTimeField(auto_now=True, help_text='Subject last updated Timestamp')),
                ('subject_class', models.ForeignKey(help_text='Class of the subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.schoolclass')),
                ('subject_course', models.ForeignKey(help_text='Course of the subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.course')),
                ('subject_student', models.ForeignKey(help_text='Student of the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='students.student')),
                ('subject_teacher', models.ForeignKey(help_text='Teacher of the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher')),
            ],
        ),
    ]
