# Generated by Django 5.0.14 on 2025-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(db_index=True, help_text='This is the name of the subject', max_length=100),
        ),
    ]
