# Generated by Django 5.0.14 on 2025-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, help_text=' Optional Program short code e.g CIT-001', max_length=20, null=True, unique=True),
        ),
    ]
