# Generated by Django 5.0.14 on 2025-08-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level_and_more'),
        ('students', '0002_student_student_club'),
        ('subjects', '0002_alter_subject_subject_name'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(help_text='Class of the subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_student',
            field=models.ForeignKey(help_text='Student of the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(help_text='Teacher of the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Available', help_text='Aailable for registration or !', max_length=20),
        ),
    ]
