# Generated by Django 5.0.14 on 2025-08-31 08:32

import django.db.models.deletion
import django.utils.timezone
import parents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.CharField(default=parents.models.generate_unique_parent_id, editable=False, help_text='parent identifer in the system', max_length=20, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(default='07', help_text='primary phonenumber for communication', max_length=15)),
                ('parent_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor'), ('Other', 'Other')], default='Father', help_text='Parents relationship to children', max_length=20)),
                ('parent_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Suspended', help_text="parent's status in the system", max_length=15)),
                ('parent_address', models.CharField(help_text='Home address or location', max_length=255, null=True, unique=True)),
                ('parent_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Day on added to system')),
                ('parent_updated_date', models.DateTimeField(auto_now=True, help_text='Last time record was updated ')),
                ('user', models.OneToOneField(blank=True, help_text='inherited user account', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
