# Generated by Django 5.0.14 on 2025-08-23 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_address',
            field=models.CharField(help_text='Home address or location', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Day on added to system'),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(help_text='parent identifer in the system', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_phone',
            field=models.CharField(default='07', help_text='primary phonenumber for communication', max_length=15),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor'), ('Other', 'Other')], default='Father', help_text='Parents relationship to children', max_length=20),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Suspended', help_text="parent's status in the system", max_length=15),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_updated_date',
            field=models.DateTimeField(auto_now=True, help_text='Last time record was updated '),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='inherited user account', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
