# Generated by Django 5.0.14 on 2025-08-23 07:23

import parents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(default=parents.models.generate_unique_parent_id, editable=False, help_text='parent identifer in the system', max_length=20, primary_key=True, serialize=False),
        ),
    ]
