# Generated by Django 5.0.14 on 2025-08-23 19:20

import cats.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level_and_more'),
        ('courses', '0002_alter_course_course_name'),
        ('subjects', '0002_alter_subject_subject_name'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cat_id', models.CharField(default=cats.models.generate_unique_cat_id, help_text='A unique id for each cat', max_length=20, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(help_text='CAT name (e.g., CAT1, CAT2, Weekly Test).', max_length=100)),
                ('cat_term', models.CharField(choices=[('Pre-lim', 'Pre-lim'), ('Mid-Term', 'Mid-Term'), ('End-Term', 'End-Term')], db_index=True, help_text='Academic term E.G Mid-Term. ', max_length=20)),
                ('cat_year', models.IntegerField(db_index=True, default=2025, help_text='Year done e.g. 2025')),
                ('cat_max_score', models.PositiveIntegerField(default=0, help_text='Possible maximum score')),
                ('cat_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date cat was taken')),
                ('cat_updated_date', models.DateTimeField(auto_now=True, help_text='Last time cat record was updated')),
                ('cat_class', models.ForeignKey(help_text='Class associated with the cat', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='classes.schoolclass')),
                ('cat_course', models.ForeignKey(help_text='Course associated with the cat', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='courses.course')),
                ('cat_subject', models.ForeignKey(help_text='Subject associated with the cat', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='subjects.subject')),
                ('cat_teacher', models.ForeignKey(help_text='Teacher associated with the cat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='teachers.teacher')),
            ],
        ),
    ]
