# Generated by Django 5.0.14 on 2025-08-23 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_percentage_score',
            field=models.PositiveIntegerField(default=0, help_text='Cat percentage score'),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score awarded (0.00 to 100.00).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_student',
            field=models.ForeignKey(help_text='Student assigned the cat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='students.student'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_teacher',
            field=models.ForeignKey(help_text='Teacher associated with the cat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cats', to='teachers.teacher'),
        ),
    ]
