# Generated by Django 5.0.14 on 2025-08-23 12:13

import clubs.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(default=clubs.models.generate_unique_club_id, editable=False, help_text='A unique identifier for every club in the school', max_length=20, primary_key=True, serialize=False)),
                ('club_name', models.CharField(help_text='Name of the club e.g Drama, Science', max_length=100, unique=True)),
                ('club_description', models.TextField(blank=True, help_text='Short description of the club', max_length=300, null=True)),
                ('club_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='whether the club is active/inactive', max_length=20)),
                ('club_creation_date', models.DateField(default=django.utils.timezone.now, help_text='clubs creation timestamp')),
                ('club_update_date', models.DateTimeField(auto_now=True, help_text='Last time the club was updated')),
                ('club_patron', models.ForeignKey(blank=True, help_text='The patron of the club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patron_clubs', to='teachers.teacher')),
                ('club_school', models.ForeignKey(help_text='the school ownign the club', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='schools.school')),
            ],
        ),
    ]
