# Generated by Django 5.0.14 on 2025-08-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.TextField(blank=True, help_text='Short description of the club', max_length=300, null=True),
        ),
    ]
