# Generated by Django 5.0.14 on 2025-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('school', 'School'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('SysAdmin', 'SysAdmin')], help_text='Usertype selection for allauth modularity', max_length=10),
        ),
    ]
