# Generated by Django 5.0.14 on 2025-08-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parent',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
