# Generated by Django 5.0.14 on 2025-08-31 07:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=accounts.models.generate_unique_user_id, editable=False, help_text='Unique User id', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('school', 'School'), ('parent', 'Parent'), ('sysadmin', 'Sysadmin')], help_text='Usertype selection for allauth modularity', max_length=10),
        ),
    ]
