# Generated by Django 5.0.14 on 2025-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_index=True, help_text='Educational level e.g 7,8,9', unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], db_index=True, default='Active', help_text='Class status (Active or Archived).', max_length=10),
        ),
    ]
