# Generated by Django 5.0.14 on 2025-08-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Teache assigned to the class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_t', to='teachers.teacher'),
        ),
    ]
