# Generated by Django 5.0.14 on 2025-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_name',
            field=models.CharField(default='Grade', help_text='The name of the class e.g -stoic-room ', max_length=50),
        ),
    ]
