# Generated by Django 5.0.14 on 2025-08-23 10:31

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_schoolclass_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_id',
            field=models.CharField(default=classes.models.generate_unique_class_id, help_text='Unique identifier for the class', max_length=20, primary_key=True, serialize=False),
        ),
    ]
