# Generated by Django 5.0.14 on 2025-08-23 11:52

import django.db.models.deletion
import django.utils.timezone
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_alter_schoolclass_class_id'),
        ('courses', '0002_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(default=exams.models.generate_unique_exam_id, help_text='Unique id for each exam', max_length=20, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(help_text='Exam name (e.g., End-Term 1, Zonal CAT 2025).', max_length=100)),
                ('exam_term', models.CharField(choices=[('Pre-lim', 'Pre-lim'), ('Mid-Term', 'Mid-Term'), ('End-Term', 'End-Term')], help_text='Academic term E.G Term-1. ', max_length=20)),
                ('exam_year', models.IntegerField(default=2025, help_text='Year done e.g. 2025')),
                ('exam_type', models.CharField(choices=[('CAT', 'CAT'), ('Internal', 'Internal'), ('Zonal', 'Zonal'), ('National', 'National'), ('Project', 'Project')], default='Internal', help_text='Exam type e.g zonal', max_length=20)),
                ('exam_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Scheduled', help_text='Current status of the exam.', max_length=20)),
                ('exam_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Exam creation timestamp.')),
                ('exam_updated_date', models.DateTimeField(auto_now=True, help_text='Last time updated')),
                ('exam_class', models.ForeignKey(help_text='Class of exams', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.schoolclass')),
                ('exam_course', models.ForeignKey(help_text='The course the exam is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
        ),
    ]
