# Generated by Django 5.0.14 on 2025-08-23 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_level_and_more'),
        ('courses', '0002_alter_course_course_name'),
        ('exams', '0001_initial'),
        ('subjects', '0002_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_max_score',
            field=models.PositiveIntegerField(default=0, help_text='Maximum possible score.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_subject',
            field=models.ForeignKey(help_text='The subject whose exam is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exam creation timestamp.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_term',
            field=models.CharField(choices=[('Pre-lim', 'Pre-lim'), ('Mid-Term', 'Mid-Term'), ('End-Term', 'End-Term')], db_index=True, help_text='Academic term E.G Mid-Term. ', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('CAT', 'CAT'), ('Internal', 'Internal'), ('Zonal', 'Zonal'), ('National', 'National'), ('Project', 'Project')], db_index=True, default='Internal', help_text='Exam type e.g zonal', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_year',
            field=models.IntegerField(db_index=True, default=2025, help_text='Year done e.g. 2025'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_course', 'exam_class', 'exam_name', 'exam_year')},
        ),
    ]
