# Generated by Django 5.0.14 on 2025-08-23 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_exam_max_score_exam_exam_subject_and_more'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_percentage_score',
            field=models.PositiveIntegerField(default=0, help_text='Exam percentage score'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score awarded (0.00 to 100.00).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_student',
            field=models.ForeignKey(help_text='Student assigned the exam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher supervising the exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_exams', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_max_score',
            field=models.PositiveIntegerField(default=0, help_text='Possible  maximum score'),
        ),
    ]
