# Generated by Django 5.0.14 on 2025-08-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_exam_percentage_score_exam_exam_score_and_more'),
        ('schools', '0002_alter_school_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_school',
            field=models.ForeignKey(help_text='The school the exam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school'),
        ),
    ]
