# Generated by Django 5.0.14 on 2025-08-24 06:54

import comms.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communication_id', models.CharField(default=comms.models.generate_unique_communication_id, help_text='Unique communication id for every comm in the table', max_length=20, primary_key=True, serialize=False)),
                ('communication_sender_id', models.CharField(help_text='This is the id of the sender', max_length=20)),
                ('communication_sender_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin')], help_text='Role of the sender', max_length=20)),
                ('communication_recipient_id', models.CharField(help_text='ID of the recipient in the communiccaation', max_length=20)),
                ('communication_recipient_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin'), ('Group', 'Group')], help_text='Role of the recipient', max_length=20)),
                ('communication_subject', models.CharField(help_text='Subject or title of the communication', max_length=200)),
                ('communication_message', models.TextField(help_text='Message to send', max_length=1000)),
                ('communication_type', models.CharField(choices=[('Message', 'Message'), ('Notification', 'Notification'), ('Reminder', 'Reminder'), ('Alert', 'Alert')], default='Message', help_text='Type of communication', max_length=20)),
                ('communication_status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read')], default='Sent', help_text='Delivery status of the communication', max_length=20)),
                ('communication_priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', help_text='Priority of the communication', max_length=20)),
                ('communication_creation_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the message was created')),
                ('communication_read_time', models.DateTimeField(blank=True, help_text='The time when the message was read', null=True)),
            ],
            options={
                'ordering': ['-communication_creation_time'],
            },
        ),
    ]
