# Generated by Django 5.0.14 on 2025-09-01 10:51

import comms.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communication_id', models.CharField(default=comms.models.generate_unique_communication_id, help_text='Unique communication id for every comm in the table', max_length=20, primary_key=True, serialize=False)),
                ('communication_sender_id', models.CharField(help_text='This is the id of the sender', max_length=20)),
                ('communication_sender_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin')], help_text='Role of the sender', max_length=20)),
                ('communication_recipient_id', models.CharField(help_text='ID of the recipient in the communiccaation', max_length=20)),
                ('communication_recipient_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin'), ('Group', 'Group')], help_text='Role of the recipient', max_length=20)),
                ('communication_subject', models.CharField(help_text='Subject or title of the communication', max_length=200)),
                ('communication_message', models.TextField(help_text='Message to send', max_length=1000)),
                ('communication_type', models.CharField(choices=[('Message', 'Message'), ('Notification', 'Notification'), ('Reminder', 'Reminder'), ('Alert', 'Alert')], default='Message', help_text='Type of communication', max_length=20)),
                ('communication_status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read')], default='Sent', help_text='Delivery status of the communication', max_length=20)),
                ('communication_priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', help_text='Priority of the communication', max_length=20)),
                ('communication_creation_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the message was created')),
                ('communication_read_time', models.DateTimeField(blank=True, help_text='The time when the message was read', null=True)),
            ],
            options={
                'ordering': ['-communication_creation_time'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationGroup',
            fields=[
                ('communication_group_id', models.CharField(default=comms.models.generate_unique_group_id, help_text='Uique group ID', max_length=20, primary_key=True, serialize=False)),
                ('communication_group_name', models.CharField(help_text="Group name e.g. 'Grade 7 Parents'", max_length=100, unique=True)),
                ('communication_group_description', models.TextField(blank=True, help_text='Details about the group', null=True)),
                ('communication_group_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the group was created')),
                ('communication_group_creator', models.ForeignKey(help_text='Creator (Teacher or School_Admin)', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Communication Group',
                'verbose_name_plural': 'Communication Groups',
                'ordering': ['-communication_group_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communicator_member_id', models.CharField(help_text='Member ID', max_length=20)),
                ('communicator_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin')], max_length=20)),
                ('communicator_status', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=20)),
                ('communicator_join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('communicator_group', models.ForeignKey(help_text='The group of belonging', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='comms.communicationgroup')),
            ],
            options={
                'unique_together': {('communicator_group', 'communicator_member_id')},
            },
        ),
    ]
