# Generated by Django 5.0.14 on 2025-08-24 07:57

import comms.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationGroup',
            fields=[
                ('communication_group_id', models.CharField(default=comms.models.generate_unique_group_id, help_text='Uique group ID', max_length=20, primary_key=True, serialize=False)),
                ('communication_group_name', models.CharField(help_text="Group name e.g. 'Grade 7 Parents'", max_length=100, unique=True)),
                ('communication_group_description', models.TextField(blank=True, help_text='Details about the group', null=True)),
                ('communication_group_creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the group was created')),
                ('communication_group_creator', models.ForeignKey(help_text='Creator (Teacher or School_Admin)', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Communication Group',
                'verbose_name_plural': 'Communication Groups',
                'ordering': ['-communication_group_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communicator_member_id', models.CharField(help_text='Member ID', max_length=20)),
                ('communicator_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Student', 'Student'), ('School_Admin', 'School_Admin')], max_length=20)),
                ('communicator_status', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=20)),
                ('communicator_join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('communicator_group', models.ForeignKey(help_text='The group of belonging', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='comms.communicationgroup')),
            ],
            options={
                'unique_together': {('communicator_group', 'communicator_member_id')},
            },
        ),
    ]
