# Generated by Django 5.0.14 on 2025-08-31 08:32

import django.db.models.deletion
import schools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(default=schools.models.generate_unique_school_id, editable=False, help_text='A unique identifier for every school system', max_length=20, primary_key=True, serialize=False)),
                ('school_code', models.CharField(help_text='Official MOE school code.', max_length=20, unique=True)),
                ('school_name', models.CharField(db_index=True, help_text='Official school name.', max_length=150)),
                ('school_type', models.CharField(choices=[('Pre-Pri', 'Pre-Pri'), ('Primary', 'Primary'), ('Junior-SS', 'Junior-SS'), ('Senior-SS', 'Senior-SS'), ('Internatioanal', 'Internatioanal')], help_text='Type of school i.e P-PR,JSS,SSC,', max_length=20)),
                ('school_category', models.CharField(choices=[('Day', 'Day'), ('Boarding', 'Boarding'), ('Day & Boarding', 'Day & Boarding')], help_text='School Category i.e public, private', max_length=20)),
                ('school_ownership', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Community', 'Community'), ('Mission', 'Mission'), ('Others', 'Others')], help_text='School ownership i.e Public, Private', max_length=20)),
                ('school_admins', models.TextField(help_text='Comma separated list of admins username/emails-simplified for now')),
                ('school_county', models.CharField(help_text='County where the school is located.', max_length=50)),
                ('school_subcounty', models.CharField(help_text='Sub-county for finer location granularity.', max_length=50)),
                ('school_ward', models.CharField(blank=True, help_text='Optional ward fill for zonal exams management', max_length=50, null=True)),
                ('school_location', models.CharField(help_text='Location of school residence.', max_length=255)),
                ('school_phone', models.CharField(help_text='Official  School tell NO.', max_length=20)),
                ('school_status', models.CharField(choices=[('Pending', 'Pending Validation'), ('Active', 'Verified'), ('Suspended', 'Suspended')], default='Pending', help_text='School_status on the platform e.g Verified', max_length=20)),
                ('school_principal', models.CharField(help_text='Name of the toplevel Admin', max_length=100)),
                ('school_creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date/time stamp')),
                ('school_updated_date', models.DateTimeField(auto_now=True, help_text='Last Modification timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
