# Generated by Django 5.0.14 on 2025-08-23 07:23

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(default=schools.models.generate_unique_school_id, editable=False, help_text='A unique identifier for every school system', max_length=20, primary_key=True, serialize=False),
        ),
    ]
