# Generated by Django 5.0.14 on 2025-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(db_index=True, help_text='Official school name.', max_length=150),
        ),
    ]
