# Generated by Django 5.0.14 on 2025-08-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_subcouty',
            new_name='school_subcounty',
        ),
    ]
