# Generated by Django 5.0.14 on 2025-08-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_school_subcouty_school_school_subcounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_status',
            field=models.CharField(choices=[('Pending', 'Pending Validation'), ('Active', 'Verified'), ('Suspended', 'Suspended')], default='Pending', help_text='School_status on the platform e.g Verified', max_length=20),
        ),
    ]
